### ISSUE TITLE
F3-CT-Issue-1: SAFI-76 only in Option C

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#1]
* Add text to clarify the operational of CT under topologies for option A, B, or C
* Expand current Add Paths Example for service and transport AFI/SAFI families
* Add text on why RFC8277 (Appendix)
* Explanation of how RD can be used as an end-to-end distinguisher. In this explanation, please
   explain what happens at border routers (BRs).

**Comment by suehares** [comment]
This issue is closed with draft-ietf-idr-bgp-ct-17
