### ISSUE TITLE
F3-WG-Issue-4-CT: Intent at Service level [Ketan Talaulikar]

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#10]
* Chair + Ketan: Define an example of a service layer intent versus transport intent.
* CT: Add a section to discuss how color is implement in the VPN service layer.
* CT: Add a definition of intent that aligns with Spring and other IETF/IRTF WGs

**Comment by suehares** [comment]
This comment is awaiting a review by Ketan Talaulikar for this issue.  If we do not have this during WG LC, I will again ask for a review and then close the issue.

**Comment by kalirajv** [comment]
Closing: https://mailarchive.ietf.org/arch/msg/idr/oWnDXnF4ROYd-wK16MNz18510SA/
