### ISSUE TITLE
F3-WG-Issue-5-CT: Technology BGP-CT and CAR are based [upon] and implications [Jeffrey Zhang]

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#11]
* Chair + Jeffrey Zhang: define an example of RD, RTCs, and labels passed by VPN services that might interact with CT and CAR domains. This example must consider that CAR does not support VPN semantics.
* CT: Clarify the interaction with RDs and RTCs by discussing how CT handles RDs, RTCs, labels and other VPN signaling information that sent to domain with CT.
* CT discuss how efficient CT is in domains which do not handle SR-MPLS or VPNs.

**Comment by suehares** [comment]
This issue is closed with the publication of draft-ietf-idr-bgp-ct-12.
