### ISSUE TITLE
F3-WG-Issue-6-CT: Benefits of Route Targets [Swadesh Agrawal]

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#12]
* Chair + Keyur Patel + Swadesh Agrawal – Review F3-WG-issues-6 to generalize example for the use of Route Targets.
* CT: Provide normative text and examples for non-agreeing color domains with examples on how transport class is used. These examples should include the original example in F3-WG-issue-6 (multiple Transport class RTs) which includes attaching multiple TC RTs to be used in different color domains and the generalized RT example.

**Comment by suehares** [comment]
This issue awaits reviews by Keyur Patel and Swadesh.

**Comment by kalirajv** [comment]
This part has reached consensus on IDR WG mailing list. But will track if anything remaining as part of Issue#6 which is also tracking F3-CT-Issue-6 (The RD part).
