### ISSUE TITLE
F3-WG-Issue-7-CT: Compatibility of BGP-CT and BGP-CAR to SR-PCE (Shraddha Hegde)

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#13]
* CT: Consider how CT implements or interoperates with all the constructs in RFC 9256. Provide a short section in your document regarding support.
* CT: Describe the limits of any community, extended community, wide-community regarding color when interacting with CT’s mapping community.

**Comment by suehares** [comment]
with the publication of draft-ietf-idr-bgp-ct-12  this issue is closed.
