### ISSUE TITLE
F3-WG-Issue-8-CT: Scaling and Expected Route size

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#14]
CT: Discuss in scale section how CT scales to:
 * limits in draft-hr-spring-intentaware-routing-using-color-00
 * Jeff Haas’ rough route calculation: 1.5 million routes, given 10K update, about 2.5 minutes of convergence
 *  Robert’s use case: transient route problems every 5-10 sections every 50 seconds

**Comment by suehares** [comment]
draft-ietf-idr-bgp-ct-17 resolves this issue.  Further issues should be raised based on this draft.
