### ISSUE TITLE
F3-CT-Issue-2: Scaling Discussion

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#2]
* Add text on why CT uses RFC8277 (Appendix) that includes scaling discussion.  Sizing discussion should reference the following (at least): draft-hr-spring-intentaware-routing-using-color-00#section-6.3.2, and packing for SRv6 SIDs

**Comment by suehares** [comment]
This issue is closed with the publication of draft-ietf-idr-ct-12.  A review of the text by Jeff Haas, Keyur Patel, and Jie Dong may cause this issue to be reopened.
