### ISSUE TITLE
rfc8664/SRTE Color

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-idr/draft-ietf-idr-bgp-ct#26]
https://github.com/ietf-wg-idr/draft-ietf-idr-bgp-ct/blob/0cda9b95957203599f9418b0781d5575eab75557/draft-ietf-idr-bgp-ct.txt#L626C1-L627C32

There is no SRTE Color in this RFC. Which part are you referring to?

**Comment by neonatty** [comment]
Updated the correct draft link in latest commit.
