### ISSUE TITLE
followup to #28

### ISSUE THREAD

**Issue by gregbo** [ietf-wg-idr/draft-ietf-idr-bgp-ct#29]
The changes I proposed in #28 reflect my review of roughly half of the draft.  Time permitting, I will review the remainder of the draft, and propose additional changes if needed.  I also have some additional issues to raise:

- I thought some text in the "Scaling Considerations" section suggested normative requirements, even though the normative directives weren't used.  Perhaps you could explain why these considerations aren't normative.
- In the Introduction (and several other places), there are references to options A, B, and C from RFC 4364.  The (literal) text of RFC 4364 does not contain that wording, although there is router literature that makes the same references.  Readers who are not familiar with this literature might be concerned about this, so I hope the change I made (adding "a.k.a. multi-AS") makes the reference clearer.  Possibly, this is an issue to be addressed if a 4364bis is ever considered.

**Comment by kalirajv** [comment]
Thanks for the review Greg. Really appreciate it.

We will review and pull the suggested changes.

Thanks
Kaliraj

**Comment by kalirajv** [comment]
These changes were pulled. Thanks for the text edits Greg. 

Will close this issue.

Thanks
Kaliraj
