### ISSUE TITLE
F3-CT-Issue-3: BGP-CT and RTC

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#3]
* Expand Section 18.3 in draft-ietf-idr-bgp-ct-00 to indicate the lack of need for “an IP address specific RT” for scenario given by Jeffrey Zhang.
*  Clarifying section 14.2 to address Swadesh comments regarding RTs with “<eSN>:<TC> Clarifying should be alignment with F3-CT-Issue-2

**Comment by suehares** [comment]
This issue is closed with the publication of draft-ietf-idr-bgp-ct-12.
