### ISSUE TITLE
color community documentation

### ISSUE THREAD

**Issue by jhaas-pfrc** [ietf-wg-idr/draft-ietf-idr-bgp-ct#32]
The BGP color community is referred to multiple times in the -ct document.  Here's an example:

> CE31 can attach a Mapping Community Color:0:100 on this route, to indicate its request for Gold SLA

However, this textual canonicalization is not IETF neutral.  The intent here is to say the color extended community as defined in RFC 9012 with the Flags field set to 0 and the color field set to 100.

At least one explanation of this notation should be made in the document prior to its use.

**Comment by kalirajv** [comment]
Incorporated comment, replied on IDR list: 

https://mailarchive.ietf.org/arch/msg/idr/I84ya1TAXicc8YcEYiI-fRGvmII/

Pls take a look.

Thanks
Kaliraj
