### ISSUE TITLE
transport-target documentation

### ISSUE THREAD

**Issue by jhaas-pfrc** [ietf-wg-idr/draft-ietf-idr-bgp-ct#33]
The -ct draft largely discusses the normative procedures vs. the "transport class" throughout much of the document.  A few references in the document, not clearly defined until later, casually mention "transport-target".  We get past section definition in  4.3 to section 5.1 before we realize that transport-target is intended to be an extended community implementing a transport class.

Ideally, one bit of wording should be picked and carried consistently throughout the document.

**Comment by jhaas-pfrc** [comment]
Note: Similar to the color community issue, the middle field of 0 should be discussed in the notation before first use.

**Comment by kalirajv** [comment]
Incorporated comment, replied on IDR list: 

https://mailarchive.ietf.org/arch/msg/idr/I84ya1TAXicc8YcEYiI-fRGvmII/

Pls take a look.

Thanks
Kaliraj
