### ISSUE TITLE
Remove reference to non-defined wide communities route-target

### ISSUE THREAD

**Issue by jhaas-pfrc** [ietf-wg-idr/draft-ietf-idr-bgp-ct#34]
> The RT carrying <eSN>:<TC> MAY be an IP-address specific regular RT (BGP attribute code 16), IPv6-address specific RT (BGP attribute code 25), or a Wide-communities based RT (BGP attribute code 34) as described in [Route Target Constrain Extension](https://tools.ietf.org/html/draft-zzhang-idr-bgp-rt-constrains-extension-03#section-2) [[RTC-Ext](https://tools.ietf.org/html/draft-zzhang-idr-bgp-rt-constrains-extension-03#section-2)]. This document recommends using Wide-communities based RT for the same.

Wide communities define a community format, but do not implement various community types in the main document.  Thus, there is no such thing as a wide communities route-target at this time.  References to it should be removed from -ct.

Secondarily, the esn:tc format should discuss that the Local Administrator field of an ipv4/ipv6 extended community type can only carry two octets of information, and thus the transport class/color field can only encode up to 2^16-1 rather than the full 2^32-1 space.

**Comment by kalirajv** [comment]
Incorporated comment, replied on IDR list: 

https://mailarchive.ietf.org/arch/msg/idr/I84ya1TAXicc8YcEYiI-fRGvmII/

Pls take a look.

Thanks
Kaliraj
