### ISSUE TITLE
Section 1 - Agnostic to tunneling capabilities 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#35]
Comment from Keyur Patel's review 

1)
Section 1.
 <snip>
The mechanisms defined in this document are agnostic to the tunneling
   technologies.  These can be applied homogeneously to intra-domain
   tunneling technologies used in brownfield networks as well as
   greenfield networks.  E.g.  MPLS Traffic Engineering (TE) or Segment
   Routing (SR)).
 <snip>
#Keyur: SRv6 is not supported. GRE and Vxlan not support so really not agnostic to  tunneling. Can we replace agnostic?

**Comment by suehares** [comment]
A suggestion for text change for paragraph 6 in section 1 that starts "The mechanisms defined"

Old text/E.g. MPLS Traffic Engineering (TE) or Segment Routing (SR)/ 

New text/For clarity, only some examples of tunneling capability are given within this document.  
For example, MPLS Traffic Engineering (TE) examples are described in this text.  Other tunneling 
technologies have been described in detail in other documents and overview has been included 
in the text.  For example, the details for Segment Routing (SRv6) are provided in [BGP-CT-SRv6], 
and an overview of that document is provided in section 7.13. /

**Comment by suehares** [comment]
Jie's comment on the same point 

2.	Introduction
“The mechanisms defined in this document are agnostic to the tunneling technologies. These can be applied homogeneously to intra-domain tunneling technologies used in brownfield networks as well as greenfield networks. E.g. MPLS Traffic Engineering (TE) or Segment Routing (SR)).”

Jie: The brownfield and greenfield description depends on the time and the technology used in the network first, thus may not be accurate in all cases. Suggest to remove brownfield and greenfield here.

**Comment by kalirajv** [comment]
clarified text:

"The mechanisms defined in this document allow different tunneling technologies to become Transport Class aware. These can be applied homogeneously to intra-domain tunneling technologies used in brownfield networks as well as greenfield networks. For clarity, only some tunneling technologies are detailed in this document. For example, MPLS Traffic Engineering (TE) examples are described. Other tunneling technologies have been described in detail in other documents and only an overview has been included in this document. For example, the details for Segment Routing (SRv6) are provided in [[BGP-CT-SRv6](https://tools.ietf.org/html/draft-ietf-idr-bgp-ct-srv6-00)], and an overview is provided in [Section 7.13](https://datatracker.ietf.org/doc/html/draft-ietf-idr-bgp-ct-22#SRv6-Support)."
