### ISSUE TITLE
Section 1 - Introduction - TE characteristics or Intent 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#36]
2)
Section 1.
<snip>
The constructs defined in this document are used to classify and
   group these intra-domain tunnels based on their TE characteristics
   (e.g., low latency), into identifiable classes, thus making them
   "intent-aware".
<snip>
#Keyur: Is it TE characteristics or more Services specific intent?

**Comment by suehares** [comment]
**Kaliraj response:** 

 It is TE characteristics. The tunnels have specific TE characteristics. 

The service-intent maps to some such TE-characteristics.  Operators consider a set of TE characteristics to denote a certain TransportClass. The Service Intent is what TC to use as primary and what TC to use as fallback.. etc.

**Comment by suehares** [comment]
Possible fix: 
Old Text:/ The constructs defined in this document are used to classify and group these intra-domain tunnels based on their TE characteristics (e.g. , low latency) into identifiable classes, thus making them intent-aware./

New text:/Customers need to be able to signal Intent to the network, and the network needs to have constructs able to enact the customer's intent.  The network constructs defined in this document are used
to classify and group intra-domain tunnels based on their traffic-engineering (TE) characteristics into 
identifiable classes that can pass "intent-aware" traffic.  Policy selectively maps the customer traffic with Intent classification into the "intent-aware" tunnels for these classes. 

(I'm not sure if the last is exactly what is needed.  I'm flexible about the changes.  What I'm trying to indicate is the type of changes that need to occur)

**Comment by kalirajv** [comment]
clarified text to:

Customers need to be able to signal desired Intent to the network, and the network needs to have constructs able to enact the customer's intent. The network constructs defined in this document are used to classify and group these intra-domain tunnels based on various characteristics, like TE characeteristics (e.g., low latency), into identifiable classes that can pass "intent-aware" traffic. These constructs enable services to express their desired intent on using one or more identifiable classes, and mechanisms to selectively map traffic onto "intent-aware" tunnels for these classes.
