### ISSUE TITLE
Section 2.1 - Better name for BGP Commuity Like Attribute (CLA) 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#37]
Keyur's review
 
3) Minor nit
Section 2.1.
<snip>
BGP Community Like Attribute (CLA)
<snip>
#Keyur: The use of "Like" in the attribute naming is confusing. Can we choose a better name please?

**Comment by suehares** [comment]
Kaliraj response.  
KV> It is used to suggest all BGP attributes that carry community/extended-community/large-community
KV> This term is used in draft-zzhang-idr-bgp-rt-constrains-extension-03
KV> Please suggest a different name. “Community Carrying Attribute”?

**Comment by kalirajv** [comment]
Changed to "Community Carrying Attributes", as agreed with Keyur.
