### ISSUE TITLE
Section 3 - editorial nits 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#38]
4) Minor Nits
Section 3.0.
#Keyur: Please Define L1, L2, L3, L4.
                Please Define IP1, IP2, IP3, IP4 (BGP-LU/underlay prefixes)

**Comment by suehares** [comment]
Response from Kaliraj

KV> IP1, IP2, IP3 are Service family Prefixes (e.g. AFI/SAFI: 1/1). It is shown in the figure as ‘INET Service’. I can clarify this in the text.

**Comment by suehares** [comment]
it seems that IP1, IP2, and IP3 are related to Scheme 1-3.n

Resolution Schemes              Transport Route DB
================== ==========                 
Scheme 1 (IP1) color:  0:100   (TRBD[TC-100], TRDB[TC-BE])
Scheme 2 (IP2) color:   0:200  (TRBD[TC-200], TRDB[TC-BE])
Scheme 3 (IP3)         100:200  (TRBD[TC-100], TRDB[TC-200] 
                                                           ^^^^             ^^^^^
                                                           Transport Class ID

**Comment by suehares** [comment]
Section 3.0.
<snip>
BGP CT family carries transport prefixes across tunnel domain
   boundaries (e.g., in inter-AS Option C networks), which is parallel
   to BGP LU (AFI/SAFIs 1/4 or 2/4).
<snip>
#Keyur: Please consider removing (e.g., in inter-AS Option C networks).

Kaliraj reponse: 

KV> it is helpful in clarifying BGP CT is applicable to option-C networks.
KV> This was added based on suggestions in some previous reviews. 

Sue> The paragraph starting with "BGP CT family carries transport prefixes across tunnel domains" does not hold together well.  I think you need to think about the editorial flow. 
Here's my understanding of this paragraph in the flow

1. The paragraph starting with (The underlay route ... ) introduces the concept of CT families as a way to extend an underlay tunnel to adjacent domains.  

2. This paragraph (that starts with BGP CT family) does xx as compare with BGP-LU.
3. The paragraph following (that starts with IN figure 1), gives the example. 
Is this your logic flow?

**Comment by suehares** [comment]
Merging Jon Hardwick's comments and Keyur's comments into section 3. 

**Jon Hardwick's comments:**
3 Architecture Overview - what are IP1..IP3? IP prefixes reachable via PE11?
Not sure if these should say EP1..EP3 per the terminology section.

**Keyur's editorial changes**
Section 3.0.

BGP CT family carries transport prefixes across tunnel domain
boundaries (e.g., in inter-AS Option C networks), which is parallel
to BGP LU (AFI/SAFIs 1/4 or 2/4).

#Keyur: Please consider removing (e.g., in inter-AS Option C networks).

**Kaliraj response to Keyur in email** 
KV> it is helpful in clarifying BGP CT is applicable to option-C networks.
KV> This was added based on suggestions in some previous reviews.

**Comment by suehares** [comment]
**Jie Dong's comments**

Section 3 Architecture overview

“Overlay routes carry sufficient indication of the desired Transport Classes using a BGP community which assumes the role of as a "Mapping Community". A Resolution Scheme is identified by its "Mapping Community", where its configuration can either be auto-generated based on TC ID or done manually.”

Jie: suggest to be more accurate on “a BGP community” here. Can any type of BGP community/extended community/large community be used for the role of “mapping community”.

**Comment by kalirajv** [comment]
addressed
