### ISSUE TITLE
F3-CT-Issue-4: CT NLRI Format

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#4]
* Revise CT text to indicate whether CT allows for multiple labels in NLRI

**Comment by suehares** [comment]
This issue is closed with the publication of draft-ietf-idr-bgp-ct-12. New reviews of draft-ietf-idr-bgp-ct are requested by idr chairs (Keyur Patel, Jeff Haas) and secretary (Jie Dong).   If these reviews find problems with the text, a new issues will be opened.
