### ISSUE TITLE
Section 4.3 - Major comment 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#42]
**Keyur Patel review** 
11) Major Comment
Section 4.3.
<snip>
A BGP speaker that implements RT Constraint Route Target Constraints
   [RFC4684] MUST apply the RT Constraint procedures to the Transport
   Class Route Target Extended community as well.
<snip>
**#Keyur:**
1) This text needs to be augment to account bunch of SAFIs defined in this draft.
2) If these routes need to be leaked into EBGP domains.. RTC doesn’t provide multi-paths by default and so implementation should give some guidance.
3) Also guidance should be provided about filtering of this community where needed (as it is defined as a transitive community).

**Kaliraj:** 
**On #1:**
KV> Following text mentions that:
“Constrained Route Distribution mechanisms as specified in [Route Target Constraints][[RFC4684] can be applied to BGP CT routes using its Transport Class Route Target Extended community.”.
KV> May be I can add SAFI 76 value specifically in it.

**On #2:**
2) If these routes need to be leaked into EBGP domains.. RTC doesn’t provide multi-paths by default and so implementation should give some guidance.

KV> RTC has number of external-paths config control. Which is used for CT routes also. 

**On #3** 
3) Also guidance should be provided about filtering of this community where needed (as it is defined as a transitive community).
 
KV> Since CT follows RFC8212 by default, explicit import/export policies are needed to send/receive CT routes with this community across EBGP boundaries.
KV> and the routes propagate only until the sessions where CT SAFI is negotiated, and don’t intermix with other SAFIs. I think these sections cover this aspect?

**Comment by suehares** [comment]
I think that you can place the AFI/SAFI in the first two paragraphs of the text for this section. 

Old text:/
This section defines a new type of Route Target, called "Transport Class" Route Target Extended Community.
"Transport Class" Route Target Extended Community is a transitive extended community [EXT-COMM] [[RFC4360]of extended type, which has the format as shown in [Figure 2]/

Sample location of addition of AFI/SAFI 
This section defines a new type of Route Target, called "Transport Class" Route Target Extended Community.
"Transport Class" Route Target Extended Community is a transitive extended community [EXT-COMM] [[RFC4360]of extended type, which has the format as shown in [Figure 2].  The procedures for the use of the Transport Class RTC with ____ NLRI (AFI/SAFI) are defined below./

**Comment by suehares** [comment]
Sue's Questions to Keyur (on idr list) 
1.	Are you looking for a clear statement that the “Transport Class” Route Target Extended Community only applies to a specific list of AFI/SAFI? 
2.	If so, wouldn’t a better place to that information in the first two paragraphs of this section 4.3


3.	What sub-bullets #2 and #3 under point #11 suggest to me is that the text describing the use of Transport Class RTC (Route Target Extended Community) is not clear enough 
Specifically, the text in the following paragraphs needs to be upgraded to give specific procedures.   These procedures need to be expanded to include the following:
1)	include both IBGP and EBGP transmission cases
2)	instructions on when the community should be filtered.  
**Paragraphs in question**
“The VPN route import/export mechanisms as specified in [BGP VPN][[RFC4364]] and the Constrained Route Distribution mechanisms as specified in [Route Target Constraints][RFC4684] can be applied to BGP CT routes using its Transport Class Route Target Extended community.[¶]

A BGP speaker that implements RT Constraint [Route Target Constraints] [[RFC4684] MUST apply the RT Constraint procedures to the Transport Class Route Target Extended community as well.[¶]

The Transport Class Route Target Extended community is carried on Classful Transport family routes and is used to associate them with appropriate TRDBs at receiving BGP speakers.[¶]

**Comment by kalirajv** [comment]
Clarified text by adding AFI/SAFI pairs, added text to take care of the EBGP case mentioned above. These updates were conveyed in email to IDR, and reviewed with Keyur, Sue in offline review call.
