### ISSUE TITLE
Section 5.1 (Editorial) 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#43]
****Section 5.1**.**
#Keyur: I like the concept in section 5.1 but any reason why mapping community is not preferred to be one of color, transport target, or a RT? If the mapping community is preferred (as it seems) then some descriptive text would help.
 
KV> Mapping community is not a IANA type, it is a role. So yes, either of these communities (color-ext-community, transport-class-RT) can be used as a Mapping-community.
KV> This is what is described in Sec 5.1. Not sure what I am missing..

**Comment by suehares** [comment]
**Jon Hardwick's comment** 
5.1 Mapping Community
 
   Overlay routes SHOULD NOT contain more than one Mapping Community.
   Conflicting multiple Mapping Communities may result in inconsistent
   route selection.
 
Why might route selection be inconsistent in this case? The previous paragraph mandates that the communities must be checked in order.
 
KV> That’s right. But different implementations may internally organize/order the communities in a different way.
KV> So general guidance was to not assume any specific ordering or sorting of communities. 

Earlier in this section you refer to renumbering and migration scenarios. Would that not be a use case for multiple mapping communities on an overlap route?
 
KV> In the renumbering and migration scenarios, two distinct mapping-communities will map to the same Resolution scheme.
KV> Hence irrespective of order of the communities, or which mapping-community gets chosen, route maps to same Resolution scheme unambiguously. 
KV> Just a make before break approach, assisting in graceful renumbering.

**Comment by suehares** [comment]
Sue's comment the logic flow in section 5.1 is confusing to me. 

Could you start by responding to this github comment with an outline of what you are trying to say.

**Comment by kalirajv** [comment]
Sec 5.1 describes 'Mapping Community'. It has 6 paras. This is what they do:

para 1: explains that mapping community is a 'role' that any IANA assigned community can play. 
            mapping community is not a new IANA type by itself.

para 2: explains the cardinality of mapping-community : resolution-scheme. That, it is 1:1 in normal operations, and it can be N:1 during renumbering/migration scenarios. 

para 3: gives examples of communities that may play role of mapping community.

para 4: describes how effective-mapping-community is determined for a route, also considering the  N:1 case where  more than one mapping-community on the route map to 1 resolution-scheme.

para 5 and 6: describe error conditions that should be carefully avoided during operator provisioning.

**Comment by kalirajv** [comment]
Closing based on above discussion, and some updates with clarifying text in sec 5
