### ISSUE TITLE
Section 6.2 - Error handling (required change) 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#45]
13)
Section 6.2.
#Keyur: What are error conditions in cases the nexthop length is other than specified? Will these routes accepted or still ignored? 
 
KV> rfc7606 Sec 7.11 talks about nexthop length error in MP_REACH. I don’t think bgp-ct draft needs to redefine that. Same logic should apply here also, since we are using the same MP_REACH attribute.

**Comment by kalirajv** [comment]
clarified text on unexpected nexthop length as error
