### ISSUE TITLE
F3-CT-Issue-5: Putting MPLS Label field into new SAFI format

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#5]
* Update in CT document to disallow SRv6 Transposition for SAFI 76 in BGP-CT
  * Additional details for SRv6 only example discussed by Kaliraj and Ketan – for R4 set in MPLS label field.
  * Discussion on Migration from BGP-LU (RFC3101) to RC8277 to CT
    * Indicate that LU 3107 to RFC8277 is not in the scope of this document.
    * Add a Section on Interaction with LU that includes: deployment of CT along with
LU and transition from LU to CT
    * Discuss any relevant conflict between SRv6 and MPLS-centric NLRIs
* Write notes for RFC-9252-bis:
   * Write 'document' indicating the issues of problems with SRv6 transport for RFC8277 NLRIs
     (what kind of document? errata for RFC-9252?)
   * Conflict between using SRv6 and MPLS-centric NLRIs

**Comment by suehares** [comment]
This issue will be closed after a review by Jeff Hares and Keyur Patel.  This issue will be closed by 7/24.

**Comment by kalirajv** [comment]
Closing: https://mailarchive.ietf.org/arch/msg/idr/oWnDXnF4ROYd-wK16MNz18510SA/
