### ISSUE TITLE
Section 7.7 - Avoding Loops 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#50]
**Jon Hardwick** 
7.7 Avoiding Loops Between RRs in the Forwarding Path
 
This section feels out of place in this document as it is not a problem specific to BGP-CT, it is a general BGP problem. It seems like it should be split out in a different RFC!

**Kaliraj response:** 
KV> Yeah it is not specific to but is more relevant to CT/LU deployments, because of ‘RR with nexthop-self’ usage.  I wanted to record it here because customers deployments CT may hit it easily, and this problem/solution was not already recorded anywhere.

**Comment by suehares** [comment]
19) Major Comment
Section 7.7. & 7.7.1.
#Keyur: The looping issue define in 7.7 and 7.7.1 is well understood? The solutions to these looping issues are also well understood. What is the purpose of these sections? The text in 7.7.1 is now updating a Route Reflector RFC for this SAFI? IMHO this text SHOULD be pulled out.

**Comment by suehares** [comment]
KV> It is tribal knowledge that is not documented in any draft/RFC (I was actualy surprised), And it is very important to document this, because customers may hit it in the field when deploying CT, which uses RRs with nexthop-self. So, documenting it in this draft.

**Comment by suehares** [comment]
Look carefully to see if you are updating the Route Reflector RFC for this SAFI.  

Please provide a substantial answer for this point.

**Comment by kalirajv** [comment]
Yes, section 7.7.1 updates RR RFC-4456 - as also described in the text. Providing users a way to configure path-selection such that cluster-list is compared before originator-id. Routes of SAFI 76 need this update.

**Comment by kalirajv** [comment]
Closing based on discussion in above thread, and also in offline discussion with Sue and Keyur.

Since 'RR with NexthopSelf' deployments are expected to be used with BGP-CT, it is good to keep this text, to avoid any ambiguity.
