### ISSUE TITLE
Section 8 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#51]
**Jon Hardwick:** 

8 Illustration of BGP CT Procedures
 
Should this section be an appendix? It is a great worked example, by the way.
 
KV> Readers mentioned they found this section useful to understand the workings of the protocol procedures. So would like to keep it closer to main text. 
KV> Thanks!

**Comment by kalirajv** [comment]
Closing with above explanation
