### ISSUE TITLE
section 7.8 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#52]
20)
Section 7.8.
#Keyur: Does the Mapping community need to be tied with RTC?
 
Kaliraj> No. Mapping-community doesn’t interact with RTC. Only the TC-RT interacts with RTC because it is a RT.

**Comment by suehares** [comment]
The mapping community text needs to clearly state this point. 
The TC-RT needs to discussion interactions with RTC.

**Comment by kalirajv** [comment]
clarified text in 
   https://datatracker.ietf.org/doc/html/draft-ietf-idr-bgp-ct-22#section-5.1  (last line)
