### ISSUE TITLE
Section SRv6 Support 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#54]
#Keyur: SRv6 support. Not sure what the section is trying to say from the normative pov?

KV> It is pointing to the document that explains in detail the SRv6 procedures for BGP CT.

**Comment by suehares** [comment]
Sue:  The SRv6 document was split from the main document into a separate document. 
The SRv6 is a WG document.   Therefore, the section can be an overview. 

Experimental drafts can have WG drafts that are referred to.  
The status of the SRv6 draft is also experimental.

**Comment by kalirajv** [comment]
As discussed, this section just provides an overview of SRv6 support for CT. The details of this support are in the split out draft-bgp-ct-srv6 document, which is referred to in this base bgp-ct draft in an Informative manner.
