### ISSUE TITLE
Section 7.14 - Error handling 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#55]
Based on the comments in Keyur's review, we'll need to circle back to error handling in section 7.14

I would like to address the other comments, and then review section 7.14.

**Comment by kalirajv** [comment]
nexthop length errors clarified in https://www.ietf.org/archive/id/draft-ietf-idr-bgp-ct-21.html#section-6.2 

discussed in call with keyur
