### ISSUE TITLE
Abstract + Network Slices 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#56]
Jie Dong's comment 

1.	Abstract

It talks about using BGP-CT as a construct to realize IETF network slices. As I know, the network slice framework does not mention intent-based routing mechanisms. Thus the relationship between CT and network slicing is not that clear. Suggest to remove this.

**Comment by kalirajv** [comment]
I had responded to this comment in my Nov 5 email, pasting excerpt here:

KV> It is relevant to network slicing.
    There is also mention on control plane extensions to achieve this kind of slicing - in network slicing overview draft.
    Ref: https://www.ietf.org/archive/id/draft-boucadair-teas-ietf-slicing-overview-04.html#section-6.1

**Comment by kalirajv** [comment]
Closing with above explanation.
