### ISSUE TITLE
Section 4 - Introduction 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#57]
**Jie Dong's comments** 

6.	Section 4 Transport Class

“A Transport Class is also configured with RD and import/export RT attributes. Creation of a Transport Class instantiates its corresponding TRDB and Resolution Schemes on that node.”

Jie: Suggest to provide some text about why RD and RT are configured for transport class.

**Comment by kalirajv** [comment]
This was also answered in the Nov 5 email:

    Jie: Suggest to provide some text about why RD and RT are configured for transport class.
 
    KV> I think Protocol Procedures explain in good detail how RD and RT are used.

e.g.

sec 6.4:
   "The BGP CT SAFI 76 for AFI 1 and 2 is similar in vein to BGP LU SAFI 4, in that it carries transport prefixes. The only difference is that it also carries in Route Target, an indication of which Transport Class the transport prefix belongs to and uses RD to disambiguate multiple instances of the same transport prefix in a BGP Update."

Sec 4.3:

   "The Transport Class Route Target Extended community is carried on Classful Transport family routes and is used to associate them with appropriate TRDBs at receiving BGP speakers."

**Comment by kalirajv** [comment]
Closing with above explanation
