### ISSUE TITLE
F3-WG-Issue-1-CT: New Address Families [Shunwan Zhuang]

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#7]
Provide an example of incremental deployment in domains 1, 2, and 3. Suppose that only domains 1 and 3 have been enhanced to
 * CT - Add example of incremental deployment to draft.

**Comment by suehares** [comment]
Hi Sue,

For F3-WG-Isue-1, I think section 20.2.1 of draft-ietf-idr-bgp-ct-04 has provided a detailed and appropriate example.

Best Regards,
Shunwan
