### ISSUE TITLE
NITS run on draft-ietf-idr-bgp-ct-27 has errors

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-ct#70]
### Run verbose nits 

**Check the following lines:** 
draft-ietf-idr-bgp-ct-27.txt:
-(2477): Line appears to be too long, but this could be caused by non-ascii characters in UTF-8 encoding
-(2501): Line appears to be too long, but this could be caused by non-ascii characters in UTF-8 encoding
it states: 

**References are flagged by NITs - but that could be a problem with the tool** 
  == Missing Reference: 'PE21' is mentioned on line 410, but not defined
  == Missing Reference: 'SN11' is mentioned on line 410, but not defined
  == Missing Reference: 'TC-100' is mentioned on line 434, but not defined
  == Missing Reference: 'TC-BE' is mentioned on line 433, but not defined
  == Missing Reference: 'TC-200' is mentioned on line 434, but not defined
  == Missing Reference: 'RR26' is mentioned on line 1281, but not defined
  == Missing Reference: 'RR27' is mentioned on line 1281, but not defined
  == Missing Reference: 'RR16' is mentioned on line 1281, but not defined
  == Missing Reference: 'CE41' is mentioned on line 1286, but not defined
  == Missing Reference: 'PE25' is mentioned on line 1286, but not defined
  == Missing Reference: 'P28' is mentioned on line 1286, but not defined
  == Missing Reference: 'P29' is mentioned on line 1286, but not defined
  == Missing Reference: 'P15' is mentioned on line 1286, but not defined
  == Missing Reference: 'CE31' is mentioned on line 1286, but not defined
  == Missing Reference: 'RR11' is mentioned on line 2944, but not defined
  == Missing Reference: 'RR21' is mentioned on line 2944, but not defined
  == Missing Reference: 'RR13' is mentioned on line 3043, but not defined

  == Missing Reference: 'RR23' is mentioned on line 3043, but not defined

  == Unused Reference: 'MNH' is defined on line 2778, but no explicit
     reference was found in the text

**Comment by suehares** [comment]
These errors could be caused by the NITs tooling error.  Check with tools team.

**Comment by rjsparks** [comment]
idnits cannot know if the strings were intended to be references to documents or not - it errs on the side of caution suggesting that a human look to make sure. idnits2 also assumes that _all_ text shaped like [PE21] is a reference named PE2.

The mismatch between the actual error line and the potential too long output is a known bug with idnits2 that will be addressed in idnits3. Your long line is this one:
```
[(3054, ' Registry Name: Non-Transitive Transport Class Extended Community Sub-Types\n')]
```

**Comment by rjsparks** [comment]
Also, the verbose/very verbose output are debugging tools, not idnits2 telling you that you MUST fix something. Treat that output as a way to help understand if the main output of the script tells you something is wrong.

Again, we intend to make this output more approachable with idnits3.

**Comment by suehares** [comment]
closed with Robert Sparks comment.
