### ISSUE TITLE
F3-WG-Issue-2-CT: Support for SR-v6 (Jingrong Xie)

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#8]
WG (led by Chair + Jingrong) agree upon same topology for SRv6.
 *  CT: Provide an illustration of SRv6 data plane (e.g., E2E SRv6 & intra-domain SRv6) based on a
sample topology

**Comment by suehares** [comment]
This issue will be closed on 7/24 if Jingrong Xie has not responded with a review.

**Comment by kalirajv** [comment]
Hi Sue, Fyi - 

Jingrong had provided his comments as part of https://github.com/ietf-wg-idr/draft-ietf-idr-bgp-ct/issues/22 

His review that concluded on the issue#22 thread, will apply to this issue#8 as-well.

Thanks
Kaliraj

**Comment by suehares** [comment]
closing this based on the draft-ietf-idr-bgp-ct-12. n
