### ISSUE TITLE
F3-WG-Issue-3-CT: Key Operational Differences between CAR and CT drafts (Bruno Decraene)

### ISSUE THREAD

**Issue by kalirajv** [ietf-wg-idr/draft-ietf-idr-bgp-ct#9]
* Bruno Decraene + Jeff Haas - Create common example topology (or topologies) for shared ANYCAST Service across multiple domains. This topology (or topologies) should include anycast endpoints, and non-agreeing color-domains.
* CT - Based on the common example technology, add text to draft on shared ANYCAST Service.
* CT: In the introduction to Section 14, clarify what paradigm is used for scaling in CT. (One paradigm might be indirection and hierarchy). The text should include the following:
  * descriptions of how CT’s paradigms for indirection and hierarchy are used in the network’s transport and service topology,
  * descriptions should include unique RDs and same RDs in stable and changing topologies (e.g. routing churn).
  * how scaling is impacted by NLRI changes are handled in route withdraws, refreshes, and
updates.
* CT: Add description of procedures when IP address has collision, or with same RD. (See
Bruno’s comments for details).
* CAR/CT – Should include discussion on impact on anycast endpoints, non-agreeing color- domains.

**Comment by suehares** [comment]
I have queried the list for comments by Bruno Decraene.  If he does not respond by 7/24 with input, I will close this review.

**Comment by kalirajv** [comment]
Sue has indicated that Bruno will not be providing a response.

So closing this issue.
